"use client";

import React from "react";
import { motion } from "framer-motion";
import { FileText, FileDown, File } from "lucide-react";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

// ── TXT ───────────────────────────────────────────────────────────────────────
function buildTxtReport(data) {
  const lines = [];
  lines.push("=".repeat(64));
  lines.push("        CLAUSELENS — CONTRACT ANALYSIS REPORT");
  lines.push("=".repeat(64));
  lines.push(`Generated : ${new Date().toLocaleString()}`);
  lines.push(`Risk Level: ${data.overall_risk}`);
  lines.push(`Summary   : ${data.summary}`);
  lines.push("=".repeat(64));
  lines.push("");

  (data.changes || []).forEach((c, i) => {
    lines.push(`── [${i + 1}] ${c.section}`);
    lines.push(
      `   Risk      : ${c.risk_level}   |   Type: ${c.type.toUpperCase()}   |   Recommendation: ${c.recommendation}`,
    );
    lines.push(`   Summary   : ${c.plain_english}`);
    lines.push(`   Impact    : ${c.why_it_matters}`);
    if (c.original) lines.push(`   BEFORE    : ${c.original}`);
    if (c.modified) lines.push(`   AFTER     : ${c.modified}`);
    lines.push("");
  });

  lines.push("=".repeat(64));
  lines.push("  END OF REPORT — Generated by ClauseLens");
  lines.push("=".repeat(64));
  return lines.join("\n");
}

// ── HTML ──────────────────────────────────────────────────────────────────────
function buildHtmlReport(data) {
  const riskColor = {
    CRITICAL: "#ff3366",
    MODERATE: "#ffaa00",
    MINOR: "#4488ff",
  };
  const recColor = {
    Reject: "#ff3366",
    Negotiate: "#ffaa00",
    Acceptable: "#00ff88",
  };
  const overallCfg = {
    HIGH: { color: "#ff3366", bg: "#ff336610", border: "#ff336640" },
    MODERATE: { color: "#ffaa00", bg: "#ffaa0010", border: "#ffaa0040" },
    LOW: { color: "#00ff88", bg: "#00ff8810", border: "#00ff8840" },
  };
  const oc = overallCfg[data.overall_risk] || overallCfg.LOW;

  const cards = (data.changes || [])
    .map(
      (c, i) => `
    <div class="card">
      <div class="card-top">
        <div class="card-meta">
          <span class="idx">#${i + 1}</span>
          <span class="section-name">${c.section}</span>
          <span class="badge" style="color:${riskColor[c.risk_level]};border-color:${riskColor[c.risk_level]}50;background:${riskColor[c.risk_level]}10">${c.risk_level}</span>
          <span class="type-tag">${c.type}</span>
        </div>
        <span class="rec" style="color:${recColor[c.recommendation]}">${c.recommendation}</span>
      </div>
      <p class="plain">${c.plain_english}</p>
      <div class="why-box"><strong>Why it matters:</strong> ${c.why_it_matters}</div>
      ${c.original ? `<div class="diff before"><span class="diff-label">BEFORE</span>${c.original}</div>` : ""}
      ${c.modified ? `<div class="diff after"><span class="diff-label">AFTER</span>${c.modified}</div>` : ""}
    </div>`,
    )
    .join("");

  const critical = (data.changes || []).filter(
    (c) => c.risk_level === "CRITICAL",
  ).length;
  const moderate = (data.changes || []).filter(
    (c) => c.risk_level === "MODERATE",
  ).length;
  const minor = (data.changes || []).filter(
    (c) => c.risk_level === "MINOR",
  ).length;

  return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>ClauseLens Report</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{background:#0a0a0a;color:#ededed;font-family:'Segoe UI',system-ui,sans-serif;padding:0;min-height:100vh}
.page{max-width:900px;margin:0 auto;padding:48px 32px}
.header{margin-bottom:40px;padding-bottom:28px;border-bottom:1px solid #2a2e2a}
.logo{display:inline-flex;align-items:center;gap:8px;background:#111411;border:1px solid #2a2e2a;padding:6px 14px;border-radius:8px;margin-bottom:20px}
.logo-dot{width:8px;height:8px;border-radius:50%;background:#00ff88;box-shadow:0 0 8px #00ff8880}
.logo-text{font-size:13px;font-weight:700;color:#00ff88;letter-spacing:.06em}
h1{font-size:28px;font-weight:800;color:#fff;margin-bottom:6px}
.meta{font-size:13px;color:#555}
.overview{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;background:#111411;border:1px solid #2a2e2a;border-radius:14px;padding:24px 28px;margin-bottom:28px;flex-wrap:wrap}
.ov-left h2{font-size:11px;color:#555;text-transform:uppercase;letter-spacing:.1em;margin-bottom:8px;font-weight:600}
.ov-left p{font-size:15px;color:#ccc;line-height:1.5;max-width:500px}
.risk-pill{padding:10px 20px;border-radius:10px;font-weight:800;font-size:15px;border:1px solid;letter-spacing:.04em}
.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:36px}
.stat{background:#111411;border:1px solid #2a2e2a;border-radius:12px;padding:20px;text-align:center}
.stat-num{font-size:32px;font-weight:800;line-height:1;margin-bottom:4px}
.stat-label{font-size:11px;color:#555;text-transform:uppercase;letter-spacing:.08em;font-weight:600}
.section-title{font-size:11px;font-weight:700;color:#555;text-transform:uppercase;letter-spacing:.1em;margin-bottom:16px}
.card{background:#111411;border:1px solid #2a2e2a;border-radius:12px;padding:20px 24px;margin-bottom:14px}
.card-top{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:12px;flex-wrap:wrap}
.card-meta{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.idx{font-size:11px;color:#444;font-weight:700;font-family:monospace}
.section-name{font-size:14px;font-weight:700;color:#fff}
.badge{font-size:10px;font-weight:800;padding:3px 10px;border-radius:20px;border:1px solid;text-transform:uppercase;letter-spacing:.06em}
.type-tag{font-size:11px;color:#444;text-transform:uppercase;letter-spacing:.06em}
.rec{font-weight:800;font-size:12px;white-space:nowrap}
.plain{font-size:13px;color:#999;line-height:1.65;margin-bottom:12px}
.why-box{font-size:12px;color:#666;line-height:1.6;padding:12px 14px;background:#0c0f0c;border-radius:8px;border:1px solid #222;margin-bottom:12px}
.why-box strong{color:#888}
.diff{font-size:12px;padding:12px 14px;border-radius:8px;margin-top:8px;line-height:1.6;display:flex;gap:10px}
.diff-label{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.08em;white-space:nowrap;margin-top:2px;min-width:40px}
.before{background:#ff336608;border:1px solid #ff336625;color:#ff3366aa}
.before .diff-label{color:#ff3366}
.after{background:#00ff8808;border:1px solid #00ff8825;color:#00ff88aa}
.after .diff-label{color:#00ff88}
.footer{margin-top:48px;padding-top:24px;border-top:1px solid #1a1a1a;text-align:center;color:#333;font-size:12px}
@media(max-width:600px){.page{padding:24px 16px}.overview{flex-direction:column}.stats{grid-template-columns:repeat(3,1fr)}}
</style></head><body>
<div class="page">
  <div class="header">
    <div class="logo"><div class="logo-dot"></div><span class="logo-text">CLAUSELENS</span></div>
    <h1>Contract Analysis Report</h1>
    <p class="meta">Generated ${new Date().toLocaleString()}</p>
  </div>
  <div class="overview">
    <div class="ov-left">
      <h2>Overall Risk Assessment</h2>
      <p>${data.summary}</p>
    </div>
    <div class="risk-pill" style="color:${oc.color};border-color:${oc.border};background:${oc.bg}">${data.overall_risk}</div>
  </div>
  <div class="stats">
    <div class="stat"><div class="stat-num" style="color:#ff3366">${critical}</div><div class="stat-label">Critical</div></div>
    <div class="stat"><div class="stat-num" style="color:#ffaa00">${moderate}</div><div class="stat-label">Moderate</div></div>
    <div class="stat"><div class="stat-num" style="color:#4488ff">${minor}</div><div class="stat-label">Minor</div></div>
  </div>
  <p class="section-title">Detected Changes</p>
  ${cards}
  <div class="footer">Generated by ClauseLens · AI-Powered Contract Analysis</div>
</div>
</body></html>`;
}

// ── DOCX ──────────────────────────────────────────────────────────────────────
async function buildDocx(data) {
  const children = [];

  // Title
  children.push(
    new Paragraph({
      text: "ClauseLens — Contract Analysis Report",
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    }),
  );

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated: ${new Date().toLocaleString()}`,
          color: "888888",
          size: 20,
        }),
      ],
      spacing: { after: 100 },
    }),
  );

  // Overall
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: "Overall Risk: ", bold: true, size: 22 }),
        new TextRun({
          text: data.overall_risk,
          bold: true,
          color:
            data.overall_risk === "HIGH"
              ? "FF3366"
              : data.overall_risk === "MODERATE"
                ? "FFAA00"
                : "00FF88",
          size: 22,
        }),
      ],
      spacing: { after: 100 },
    }),
  );

  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: data.summary, size: 22, color: "AAAAAA" }),
      ],
      spacing: { after: 400 },
    }),
  );

  // Changes
  (data.changes || []).forEach((c, i) => {
    const riskColor =
      c.risk_level === "CRITICAL"
        ? "FF3366"
        : c.risk_level === "MODERATE"
          ? "FFAA00"
          : "4488FF";
    const recColor =
      c.recommendation === "Reject"
        ? "FF3366"
        : c.recommendation === "Negotiate"
          ? "FFAA00"
          : "00FF88";

    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `${i + 1}. `,
            bold: true,
            size: 24,
            color: "555555",
          }),
          new TextRun({ text: c.section, bold: true, size: 24 }),
          new TextRun({
            text: `  [${c.risk_level}]`,
            bold: true,
            color: riskColor,
            size: 20,
          }),
          new TextRun({
            text: `  ${c.type.toUpperCase()}`,
            color: "666666",
            size: 18,
          }),
        ],
        spacing: { before: 300, after: 100 },
        border: { bottom: { style: "single", size: 4, color: "2a2e2a" } },
      }),
    );

    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: c.plain_english, size: 21, color: "CCCCCC" }),
        ],
        spacing: { after: 100 },
      }),
    );

    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: "Why it matters: ",
            bold: true,
            size: 20,
            color: "888888",
          }),
          new TextRun({ text: c.why_it_matters, size: 20, color: "777777" }),
        ],
        spacing: { after: 100 },
      }),
    );

    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: "Recommendation: ",
            bold: true,
            size: 20,
            color: "888888",
          }),
          new TextRun({
            text: c.recommendation,
            bold: true,
            size: 20,
            color: recColor,
          }),
        ],
        spacing: { after: 100 },
      }),
    );

    if (c.original) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: "BEFORE: ",
              bold: true,
              size: 19,
              color: "FF3366",
            }),
            new TextRun({
              text: c.original,
              size: 19,
              color: "AA6677",
              strike: true,
            }),
          ],
          spacing: { after: 80 },
        }),
      );
    }

    if (c.modified) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: "AFTER: ",
              bold: true,
              size: 19,
              color: "00FF88",
            }),
            new TextRun({ text: c.modified, size: 19, color: "00CC77" }),
          ],
          spacing: { after: 200 },
        }),
      );
    }
  });

  // Footer
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by ClauseLens · AI-Powered Contract Analysis",
          size: 18,
          color: "444444",
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
    }),
  );

  const doc = new Document({
    background: { color: "0A0A0A" },
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1000, bottom: 1000, left: 1200, right: 1200 },
          },
        },
        children,
      },
    ],
  });

  return Packer.toBlob(doc);
}

// ── PDF ───────────────────────────────────────────────────────────────────────
async function buildPdf(data) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const W = 595.28,
    H = 841.89;
  const ML = 48,
    MR = 48,
    MT = 48;
  const TW = W - ML - MR;

  const BG = rgb(0.04, 0.04, 0.04);
  const WHITE = rgb(0.93, 0.93, 0.93);
  const GREY = rgb(0.5, 0.5, 0.5);
  const DIM = rgb(0.3, 0.3, 0.3);
  const GREEN = rgb(0, 1, 0.53);
  const RED = rgb(1, 0.2, 0.4);
  const AMB = rgb(1, 0.67, 0);
  const BLUE = rgb(0.27, 0.53, 1);

  const riskRgb = { CRITICAL: RED, MODERATE: AMB, MINOR: BLUE };
  const recRgb = { Reject: RED, Negotiate: AMB, Acceptable: GREEN };
  const overRgb = { HIGH: RED, MODERATE: AMB, LOW: GREEN };

  let page = pdfDoc.addPage([W, H]);
  let y = H - MT;

  const newPage = () => {
    page = pdfDoc.addPage([W, H]);
    page.drawRectangle({ x: 0, y: 0, width: W, height: H, color: BG });
    y = H - MT;
  };

  const guard = (needed = 60) => {
    if (y < needed + 48) newPage();
  };

  const drawText = (text, opts = {}) => {
    const {
      x = ML,
      size = 11,
      color = WHITE,
      f = font,
      maxW = TW,
      align = "left",
    } = opts;
    const words = String(text).split(" ");
    let line = "";
    const lines = [];
    for (const w of words) {
      const test = line + w + " ";
      if (f.widthOfTextAtSize(test, size) > maxW && line) {
        lines.push(line.trim());
        line = w + " ";
      } else line = test;
    }
    if (line.trim()) lines.push(line.trim());
    for (const l of lines) {
      guard();
      const lw = f.widthOfTextAtSize(l, size);
      const dx = align === "center" ? (TW - lw) / 2 : 0;
      page.drawText(l, { x: x + dx, y, size, font: f, color });
      y -= size * 1.55;
    }
    return lines.length;
  };

  // Background
  page.drawRectangle({ x: 0, y: 0, width: W, height: H, color: BG });

  // Title block
  page.drawText("CLAUSELENS", {
    x: ML,
    y,
    size: 9,
    font: fontBold,
    color: GREEN,
  });
  y -= 28;
  page.drawText("Contract Analysis Report", {
    x: ML,
    y,
    size: 22,
    font: fontBold,
    color: WHITE,
  });
  y -= 20;
  page.drawText(`Generated: ${new Date().toLocaleString()}`, {
    x: ML,
    y,
    size: 9,
    font,
    color: DIM,
  });
  y -= 28;
  page.drawLine({
    start: { x: ML, y },
    end: { x: W - MR, y },
    thickness: 0.5,
    color: rgb(0.16, 0.18, 0.16),
  });
  y -= 20;

  // Overall risk box
  guard(80);
  const boxH = 56;
  page.drawRectangle({
    x: ML,
    y: y - boxH,
    width: TW,
    height: boxH,
    color: rgb(0.07, 0.09, 0.07),
    borderColor: rgb(0.16, 0.18, 0.16),
    borderWidth: 1,
    borderRadius: 6,
  });
  page.drawText("OVERALL RISK", {
    x: ML + 16,
    y: y - 16,
    size: 8,
    font: fontBold,
    color: GREY,
  });
  page.drawText(data.summary, {
    x: ML + 16,
    y: y - 30,
    size: 10,
    font,
    color: rgb(0.8, 0.8, 0.8),
  });
  const orColor = overRgb[data.overall_risk] || GREEN;
  const orLabel = data.overall_risk || "LOW";
  const orW = fontBold.widthOfTextAtSize(orLabel, 13);
  page.drawText(orLabel, {
    x: W - MR - orW - 16,
    y: y - 26,
    size: 13,
    font: fontBold,
    color: orColor,
  });
  y -= boxH + 20;

  // Stats row
  guard(60);
  const stats = [
    {
      label: "CRITICAL",
      count: (data.changes || []).filter((c) => c.risk_level === "CRITICAL")
        .length,
      color: RED,
    },
    {
      label: "MODERATE",
      count: (data.changes || []).filter((c) => c.risk_level === "MODERATE")
        .length,
      color: AMB,
    },
    {
      label: "MINOR",
      count: (data.changes || []).filter((c) => c.risk_level === "MINOR")
        .length,
      color: BLUE,
    },
  ];
  const sW = (TW - 16) / 3;
  stats.forEach((s, i) => {
    const sx = ML + i * (sW + 8);
    page.drawRectangle({
      x: sx,
      y: y - 52,
      width: sW,
      height: 52,
      color: rgb(0.07, 0.09, 0.07),
      borderColor: rgb(0.16, 0.18, 0.16),
      borderWidth: 1,
      borderRadius: 6,
    });
    const numW = fontBold.widthOfTextAtSize(String(s.count), 22);
    page.drawText(String(s.count), {
      x: sx + sW / 2 - numW / 2,
      y: y - 26,
      size: 22,
      font: fontBold,
      color: s.color,
    });
    const lbW = font.widthOfTextAtSize(s.label, 8);
    page.drawText(s.label, {
      x: sx + sW / 2 - lbW / 2,
      y: y - 42,
      size: 8,
      font,
      color: GREY,
    });
  });
  y -= 72;

  page.drawText("DETECTED CHANGES", {
    x: ML,
    y,
    size: 8,
    font: fontBold,
    color: DIM,
  });
  y -= 16;

  // Change cards
  for (let i = 0; i < (data.changes || []).length; i++) {
    const c = data.changes[i];
    guard(100);

    // Card bg
    const startY = y;
    const estimatedH = 90 + (c.original ? 30 : 0) + (c.modified ? 30 : 0);
    page.drawRectangle({
      x: ML,
      y: startY - estimatedH,
      width: TW,
      height: estimatedH,
      color: rgb(0.07, 0.09, 0.07),
      borderColor: rgb(0.16, 0.18, 0.16),
      borderWidth: 1,
      borderRadius: 6,
    });

    y -= 14;
    // Section + badges inline
    const secText = `${i + 1}. ${c.section}`;
    page.drawText(secText, {
      x: ML + 12,
      y,
      size: 11,
      font: fontBold,
      color: WHITE,
    });
    const secW = fontBold.widthOfTextAtSize(secText, 11);
    page.drawText(c.risk_level, {
      x: ML + 12 + secW + 10,
      y,
      size: 9,
      font: fontBold,
      color: riskRgb[c.risk_level] || GREY,
    });
    const rW = fontBold.widthOfTextAtSize(c.risk_level, 9);
    page.drawText(c.type.toUpperCase(), {
      x: ML + 12 + secW + 10 + rW + 10,
      y,
      size: 8,
      font,
      color: DIM,
    });
    // Recommendation right aligned
    const recLabel = c.recommendation;
    const recW2 = fontBold.widthOfTextAtSize(recLabel, 9);
    page.drawText(recLabel, {
      x: W - MR - recW2 - 12,
      y,
      size: 9,
      font: fontBold,
      color: recRgb[c.recommendation] || GREY,
    });
    y -= 14;

    // Plain english
    const savedY = y;
    drawText(c.plain_english, {
      x: ML + 12,
      size: 10,
      color: rgb(0.65, 0.65, 0.65),
      maxW: TW - 24,
    });
    y -= 4;

    // Why it matters
    drawText(`Why: ${c.why_it_matters}`, {
      x: ML + 12,
      size: 9,
      color: GREY,
      maxW: TW - 24,
    });
    y -= 4;

    if (c.original) {
      drawText(`BEFORE: ${c.original}`, {
        x: ML + 12,
        size: 9,
        color: rgb(0.7, 0.3, 0.4),
        maxW: TW - 24,
      });
      y -= 2;
    }
    if (c.modified) {
      drawText(`AFTER: ${c.modified}`, {
        x: ML + 12,
        size: 9,
        color: rgb(0.2, 0.7, 0.4),
        maxW: TW - 24,
      });
    }
    y -= 18;
  }

  // Footer
  guard(30);
  y -= 10;
  page.drawLine({
    start: { x: ML, y },
    end: { x: W - MR, y },
    thickness: 0.5,
    color: rgb(0.16, 0.18, 0.16),
  });
  y -= 14;
  const footText = "Generated by ClauseLens · AI-Powered Contract Analysis";
  const ftW = font.widthOfTextAtSize(footText, 8);
  page.drawText(footText, { x: W / 2 - ftW / 2, y, size: 8, font, color: DIM });

  return pdfDoc.save();
}

// ── util ──────────────────────────────────────────────────────────────────────
function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ── component ─────────────────────────────────────────────────────────────────
const DownloadButtons = ({ data }) => {
  const stamp = new Date().toISOString().slice(0, 10);

  const downloadTxt = () => {
    downloadBlob(
      new Blob([buildTxtReport(data)], { type: "text/plain" }),
      `clauselens-${stamp}.txt`,
    );
  };

  const downloadHtml = () => {
    downloadBlob(
      new Blob([buildHtmlReport(data)], { type: "text/html" }),
      `clauselens-${stamp}.html`,
    );
  };

  const downloadDocx = async () => {
    try {
      const blob = await buildDocx(data);
      downloadBlob(blob, `clauselens-${stamp}.docx`);
    } catch (e) {
      console.error("DOCX error:", e);
    }
  };

  const downloadPdf = async () => {
    try {
      const bytes = await buildPdf(data);
      downloadBlob(
        new Blob([bytes], { type: "application/pdf" }),
        `clauselens-${stamp}.pdf`,
      );
    } catch (e) {
      console.error("PDF error:", e);
    }
  };

  const btns = [
    {
      label: "PDF",
      icon: FileDown,
      onClick: downloadPdf,
      title: "Download PDF report",
    },
    {
      label: "DOCX",
      icon: FileText,
      onClick: downloadDocx,
      title: "Download Word document",
    },
    {
      label: "HTML",
      icon: FileDown,
      onClick: downloadHtml,
      title: "Styled HTML report",
    },
    {
      label: "TXT",
      icon: File,
      onClick: downloadTxt,
      title: "Plain text report",
    },
  ];

  return (
    <div className="flex gap-2 flex-wrap">
      {btns.map(({ label, icon: Icon, onClick, title }) => (
        <motion.button
          key={label}
          whileHover={{ scale: 1.05, borderColor: "rgba(0,255,136,0.5)" }}
          whileTap={{ scale: 0.95 }}
          onClick={onClick}
          title={title}
          className="flex items-center gap-1.5 px-3 py-2 rounded-lg border border-[#2a2e2a] bg-[#0c0f0c] text-neutral-300 text-xs font-semibold hover:text-[#00ff88] transition-all"
        >
          <Icon className="w-3.5 h-3.5" />
          {label}
        </motion.button>
      ))}
    </div>
  );
};

export default DownloadButtons;
